name: Build LaTeX document
on: [ push ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document (literature_review)
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: latex/literature_review
          work_in_root_file_dir: true
          root_file: main.tex