name: Build LaTeX document
on: [ push ]
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document (literature_review)
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: latex/literature_review
          work_in_root_file_dir: true
          root_file: main.tex
      - name: Compile LaTeX document again for refs(literature_review)
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: latex/literature_review
          work_in_root_file_dir: true
          root_file: main.tex
          args: -pdf -file-line-error -f -interaction=nonstopmode
      - name: Push generated PDF
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add latex/literature_review/
          git commit -m "Update generated PDF"
          git push